// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;

public class PlayerJumpAction : PlayerAction
{
	public PlayerJumpAction (PlayerController player, string key) : base(player, key) {
	}

	//For Kinematic RigidBody
	public override void Perform ()
	{
		bool isJumpButtonDown = IsJumpButtonDown();
		bool isJumpButtonUp = IsJumpButtonUp();

		if (isJumpButtonDown && player.isGrounded) {
			player.velocity.y = player.initialJumpVelocity;
		} else if (isJumpButtonUp) {
			if (player.velocity.y > 0) 
				player.velocity.y /= 2f;
		}
	}

	public override void Perform(PlayerInput input) {
		bool isJumpButtonDown = input.isJumpButtonDown;
		bool isJumpButtonUp = input.isJumpButtonUp;

		if (isJumpButtonDown && player.isGrounded) {
			player.velocity.y = player.initialJumpVelocity;
		} else if (isJumpButtonUp) {
			if (player.velocity.y > 0) 
				player.velocity.y /= 2f;
		}
	}

	private bool IsJumpButtonDown() {
		if (GameInformation.instance.isControlledByPlayer) {
			return Input.GetButtonDown(key);
		} else {
			return GameInformation.instance.GetCurrentPlayerInput().isJumpButtonDown;
		}
	}

	private bool IsJumpButtonUp() {
		if (GameInformation.instance.isControlledByPlayer) {
			return Input.GetButtonUp(key); 
		} else {
			return GameInformation.instance.GetCurrentPlayerInput().isJumpButtonUp;
		}
	}

	//For Dynamic RigidBody
	// public override void actionPerform() {
	// 	if (Input.GetButton (key)) {
	// 		if (Input.GetButtonDown(key) && player.isGrounded && !this.isJumpTriggered) {
	// 			jump (6f);
	// 		}
	// 		else if (this.isJumpPressed && player.frameCount >= 1 && player.frameCount < 6)
	// 		{
	// 			//player.getRigidBody2D().AddForce(new Vector2(0,1f),ForceMode2D.Impulse);
	// 			//player.frameCount++;
	// 		}
	// 	} else if (Input.GetButtonUp (key)) {
	// 		this.isJumpPressed = false;
	// 		this.isJumpTriggered = false;
	// 	}
	// }
}




