// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;

public class PlayerJumpBehavior : PlayerActionBehavior
{
	private bool isJumpPressed;
	private bool isJumpTriggered;

	public PlayerJumpBehavior (PlayerController player, string key) : base(player, key)
	{
		this.isJumpPressed = false;
		this.isJumpTriggered = false;
	}

	//For Kinematic RigidBody
	public override void actionPerform ()
	{
		bool isJumpButtonDown, isJumpButtonUp;
		if (!GameInformation.instance.isControlledByPlayer) {
            isJumpButtonDown = GameInformation.instance.GetCurrentPlayerInput().isJumpButtonDown;
			isJumpButtonUp = GameInformation.instance.GetCurrentPlayerInput().isJumpButtonUp;
        } else {
            isJumpButtonDown = Input.GetButtonDown(key);
			isJumpButtonUp = Input.GetButtonUp(key);
        }

		if (isJumpButtonDown && player.isGrounded) {
			player.velocity.y = player.initialJumpVelocity;
		} else if (isJumpButtonUp) {
			if (player.velocity.y > 0) 
				player.velocity.y /= 2f;
		}

		// if (Input.GetButton (key)) {
		// 	if (Input.GetButtonDown(key) && player.isJumpable && !this.isJumpTriggered) {
		// 		jump (6f);
		// 	}
		// 	else if (this.isJumpPressed && player.frameCount >= 1 && player.frameCount < 6)
		// 	{
		// 		//player.getRigidBody2D().AddForce(new Vector2(0,1f),ForceMode2D.Impulse);
		// 		//player.frameCount++;
		// 	}
		// } else if (Input.GetButtonUp (key)) {
		// 	this.isJumpPressed = false;
		// 	this.isJumpTriggered = false;
		// }
	}

	//For Dynamic RigidBody
	// public override void actionPerform() {
	// 	if (Input.GetButton (key)) {
	// 		if (Input.GetButtonDown(key) && player.isGrounded && !this.isJumpTriggered) {
	// 			jump (6f);
	// 		}
	// 		else if (this.isJumpPressed && player.frameCount >= 1 && player.frameCount < 6)
	// 		{
	// 			//player.getRigidBody2D().AddForce(new Vector2(0,1f),ForceMode2D.Impulse);
	// 			//player.frameCount++;
	// 		}
	// 	} else if (Input.GetButtonUp (key)) {
	// 		this.isJumpPressed = false;
	// 		this.isJumpTriggered = false;
	// 	}
	// }

	// private void jump (float force)
	// {
	// 	Debug.Log ("Jump");
	// 	this.isJumpPressed = true;
	// 	this.isJumpTriggered = true;
	// 	player.isFloating = true;
	// 	player.isGrounded = false;
	// 	player.isJumpable = false;
	// 	player.getRigidBody2D ().AddForce (new Vector2 (0, force), ForceMode2D.Impulse);
	// 	player.frameCount++;
	// }
}




