// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;


public class PlayerMoveRightActionBehavior : PlayerActionBehavior
{
	public PlayerMoveRightActionBehavior(PlayerController player,string key) : base(player, key) {
		
	}

	public override void actionPerform()
	{
		if (Input.GetKey(key))
		{
			if (Input.GetKeyDown (key) ) {
				this.dissolveVelocity();
			}
		
			this.moveRight();
		}
	}
	
	private void dissolveVelocity(){
		// Dissolve existing velocity on X Coordinate.
		// Make player able to change direction immediately.
		player.getRigidBody2D().velocity = new Vector2(0,player.getRigidBody2D().velocity.y);
		//player.getRigidBody2D().AddForce (new Vector2 (player.getRigidBody2D().velocity.x * -1, 0), ForceMode2D.Impulse);
	}
	
	private void moveRight(){
		// Gradually add force to the Right until player reaches maximum velocity.
		if (player.getRigidBody2D().velocity.x < player.maxHorizontalVelocity){
			player.getRigidBody2D().AddForce (new Vector2 (player.maxHorizontalVelocity * 5, 0), ForceMode2D.Force);
		}
		else{
			player.getRigidBody2D().velocity = new Vector2 (player.maxHorizontalVelocity, player.getRigidBody2D().velocity.y);
		}
	}
	
}

